apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecast-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forecast-service
  template:
    metadata:
      labels:
        app: forecast-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: forecast
        image: forecast-service
        imagePullPolicy: Never
        ports:
        - containerPort: 8000