apiVersion: apps/v1
kind: Deployment
metadata:
  name: hash-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hash-service
  template:
    metadata:
      labels:
        app: hash-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5001"
    spec:
      containers:
      - name: hash-service
        image: hash-service
        imagePullPolicy: Never
        ports:
        - containerPort: 5001