apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: random-scaler
spec:
  scaleTargetRef:
    name: random-service

  minReplicaCount: 1
  maxReplicaCount: 5

  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.default.svc:80
      metricName: predicted_random_rate
      query: avg_over_time(predicted_random_rate[5m])
      threshold: "1"