apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-service
  template:
    metadata:
      labels:
        app: random-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: random-service
        image: random-service
        imagePullPolicy: Never
        ports:
        - containerPort: 5000